### ISSUE TITLE
1.3.4 Prerelease AutomatedScienceSampler reverting runAutoScience to False in settings.xml

### ISSUE THREAD

**Issue by Enderzt** [KerboKatz/AutomatedScienceSampler#14]
Hey all. Looking forward to using this mod to make my 1.3.1 play-through much more fun and streamlined. I am having an issue with your latest release. Some of the settings within the Settings.xml file are reverting to false without making any in game changes. The most important one being:

`<runAutoScience>false</runAutoScience>`

I have tried to manually set it to true before opening KSP and during playing and it may work for part of a mission but then it sets itself to false again. Changing it back to true has been hit or miss. In game GUI doesn't seem to be effecting the xml properly. 

Here is a copy of my recent Output_Log. 
[output_log.txt](https://github.com/KerboKatz/AutomatedScienceSampler/files/1546388/output_log.txt)

The mod seems to load and I have the options menu popup when playing or clicking the icon. It just the auto-science turning to false that's causing issues.

**Comment by Xarun** [comment]
Please turn on the debug option in the settings and attache a new output_log.txt.

**Comment by Enderzt** [comment]
While doing troubleshooting I uninstalled the Automatedscience 1.3.4 pre-release manually, and installed 1.3.3 through CKAN. I wanted to use the mod and just manually run the Dmagic experiments until 1.3.4 worked for me. 

I over wrote those files with the ones from 1.3.4 to create the output_log.txt file for you with debug on. I didn't uninstall through CKAN so they are still recognized as being installed through it, no AD mark after overwriting the files. Since reinstalling in this manner I am no longer getting the auto-science to trigger back to false. Here is the Output_log.txt anyways.


[output_log.zip](https://github.com/KerboKatz/AutomatedScienceSampler/files/1549285/output_log.zip)
